# Generated by Django 5.0.1 on 2024-02-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_billingdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='order_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
