# Generated by Django 5.0.1 on 2024-01-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_userprofile_image_userprofile_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patient/images/'),
        ),
    ]
